services:

version: "2"
services:
  remotely:
    image: translucency/remotely:latest
#    image: ershovsergey/remotely
    container_name: "${COMPOSE_PROJECT_NAME}_Remotely"
    hostname: "${COMPOSE_PROJECT_NAME}_mysql"
    ports:
      - ${HTTP_IP}:${HTTP_PORT}:5000
    volumes:
      - "${DATA_PATH}/remotely-data:/remotely-data"


